import = [ "~/.config/alacritty/themes/gruvbox_dark.toml" ]

working_directory = "/home/gad/"
live_config_reload = true

[window]
startup_mode = "Windowed"
decorations = "Full"
padding = {x = 3, y = 3}

[font]
normal      = { family = "MesloLGS NF", style = "Regular" }
bold        = { family = "MesloLGS NF", style = "Bold" }
italic      = { family = "MesloLGS NF", style = "Italic" }
bold_italic = { family = "MesloLGS NF", style = "Bold Italic" }
size = 10.0

#[colors]
#transparent_background_colors = true

[bell]
duration = 0

[mouse]
hide_when_typing = true
bindings = [
    { mouse = "Right", mods = "Control", action = "Paste" }
]

[keyboard]
bindings = [
    { key = "F11", action = "ToggleFullscreen" }
]

